apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        values:
          replicaCount: '2'
      - cluster: argo
        url: https://vc-t8lnrrytj8fwb63clf49.zlr-dc1.apps.dev.klusternetes.com
        values:
          replicaCount: '3'
      - cluster: argo2
        url: https://vc-7keockut9teuzqzp9cyx.zlr-dc1.apps.dev.klusternetes.com
        values:
          replicaCount: '4'
  template:
    metadata:
      name: '{{cluster}}-test'
    spec:
      project: default
      source:
        repoURL: https://github.com/abhi1-rithu2/project.git
        targetRevision: HEAD
        path: Ezy/project-test
        helm:
          parameters:
          - name: replicaCount
            value: '{{values.replicaCount}}'

      destination:
        server: '{{url}}'
        namespace: default
